### PR TITLE
Normalize filename casing for System.Configuration

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by bricelam** [comment]
(Note, I looked for other casing differences between net40 and net45, but there weren't any)

**Comment by bricelam** [comment]
@NikolaMilosavljevic Is this the right codebase?

**Comment by bricelam** [comment]
@dsplaisted Ping

**Comment by dsplaisted** [comment]
@NikolaMilosavljevic if you've forked or reimplemented this code, make sure to take this change.

**Comment by bricelam** [comment]
🎉 Thanks!

**Pull request merged**
